Tried to get as many TBCsg one - and finalize this document for a 1.0 version
ehn-digital-green-development/hcert-spec pull request #15
Opened 2021-04-12 17:10 UTC by dirkx

Our german peers are really in need of a 1.0 spec - attempt to finalize all loose ends I know of.

2021-04-12 17:19 UTC, jschlyter approved these changes

2021-04-12 20:41 UTC, gabywh requested changes
Instead of trying to fix the grammar etc here in review, I'll submit a PR as mod to this doc on a separate branch.

2021-04-12 20:41 UTC, gabywh commented on hcert_spec.md
> +The HCERT is structured and encoded as a CBOR payload with a COSE digital signature. This is commonly known as a "CBOR Web Token" (CWT), and is defined in [RFC 8392](https://tools.ietf.org/html/rfc83
payloads -> payload

2021-04-12 20:41 UTC, gabywh commented on hcert_spec.md
>  Instead - the primary validity mechanism is appearance on the most recent version of the list.
not clear what this sentence means

2021-04-12 20:41 UTC, gabywh commented on hcert_spec.md
> +Member states can use a sepearate CSCA (as per the WHO advice) - but may also use submit thier existing eMRT CSCA and/or DSC certificates; and may even chose to procure these from (commercial) trustc
ref to WHO advice?
thier -> their

2021-04-13 07:18 UTC, martin-lindstrom approved these changes

2021-04-13 07:47 UTC, fredriklj approved these changes

2021-04-13 07:52 UTC, dirkx commented on hcert_spec.md
> +The HCERT is structured and encoded as a CBOR payload with a COSE digital signature. This is commonly known as a "CBOR Web Token" (CWT), and is defined in [RFC 8392](https://tools.ietf.org/html/rfc83
fixed

2021-04-13 07:52 UTC, dirkx commented on hcert_spec.md
> +Member states can use a sepearate CSCA (as per the WHO advice) - but may also use submit thier existing eMRT CSCA and/or DSC certificates; and may even chose to procure these from (commercial) trustc
fixed

2021-04-13 08:12 UTC, merged